#!/usr/bin/python2

import dpkt
import pcapy
import socket
import sys
import datetime
import json
import pprint
import logging
import time
from logstash_async.handler import AsynchronousLogstashHandler
data = {
    'start' : datetime.datetime.today().strftime('%Y-%m-%d %H:%M:%S'),
    'flow' : {}
}
scope = ''

import threading

def logit():
    threading.Timer(30.0, logit).start()
    global data
    global logger
    now  = datetime.datetime.today().strftime('%Y-%m-%d %H:%M:%S')
    today = datetime.datetime.today().strftime('%Y-%m-%d')
    for key,item in data['flow'].iteritems():
        logger.info('netflower', extra=item)
        print(item)

def printit():
    threading.Timer(5, printit).start()
    global data
    now  = datetime.datetime.today().strftime('%Y-%m-%d %H:%M:%S')
    #print("\033c")
    ##pprint.pprint(data['flow'])
    #print ""
    #print "[ %s - %s ]" % (data['start'], now)

def recv_pkts(header,payload):
    global data,scope
    eth=dpkt.ethernet.Ethernet(str(payload))

    # Check whether IP packets: to consider only IP packets 
    if eth.type!=dpkt.ethernet.ETH_TYPE_IP:
            return 
            # Skip if it is not an IP packet

    ip = eth.data
    proto = 'tcp'
    if ip.p == dpkt.ip.IP_PROTO_UDP: # Check for UDP packets
           proto = 'udp'

    src = socket.inet_ntoa(ip.src)
    dst = socket.inet_ntoa(ip.dst)
    date = datetime.datetime.today().strftime('%Y-%m-%d')
    length = len(ip.data)
    
    if src.startswith(scope) or dst.startswith(scope):
        src_dst_format = "%s::%s::%s" % (src,dst,date)
        dst_src_format = "%s::%s::%s" % (dst,src,date)

        if scope in src:
            find_data = data['flow'].get(src_dst_format)
            if find_data is None:
                find_data = {'t': 0, 'u': 0, 'd':0} #[0,[0,0]]

            
            u = find_data['u'] + length
            d = find_data['d']
            t = find_data['t'] + length
            data['flow'][src_dst_format] = {'ip1':src,'ip2':dst,'t': t, 'u': u, 'd': d }
        else:
            find_data = data['flow'].get(dst_src_format)
            if find_data is None:
                find_data = {'t': 0, 'u': 0, 'd':0} #[0,[0,0]]

            u = find_data['u']
            d = find_data['d'] + length
            t = find_data['t'] + length
            data['flow'][dst_src_format] = {'ip1':dst,'ip2':src,'t': t, 'u': u, 'd': d }

        data['last'] = datetime.datetime.today().strftime('%Y-%m-%d %H:%M:%S')

logger = None
def main(interface):
    global logger
    logger = logging.getLogger('python-logstash-logger')
    logger.setLevel(logging.INFO)
    logger.addHandler(AsynchronousLogstashHandler('localhost', 1337, database_path='logs.db'))

    printit()
    logit()

    max_bytes = 1000000
    promiscuous = True
    read_timeout = 100 # in milliseconds
    pc = pcapy.open_live(interface, max_bytes, promiscuous, read_timeout)
 
    packet_limit = -1 # infinite
    pc.loop(packet_limit, recv_pkts) # capture packets 

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print "usage: sudo ./netflower.py [interface]"
        print "usage: sudo ./netflower.py [interface] [scope]"
        print ""
        print "example: sudo ./netflower.py wlp2s0 192.168."
        exit(1)
    try:
        interface = sys.argv[1]
        if len(sys.argv) == 3:
            scope = sys.argv[2]

        main(interface)
    except KeyboardInterrupt:
        exit(0)

